 #           Horse colic prediction

##### colic is a term used to describe a symptom of abdominal belly pain,which in horses is 
    usually caused by probelms in gastro intestinal tract.

# importing libraries

In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

## read data

In [3]:
df=pd.read_csv('C:\\users\shameena\desktop\horse.csv')
df.sample(5)

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
77,no,adult,534753,38.7,52.0,20.0,warm,NaN,normal_pink,less_3_sec,...,33.0,77.0,NaN,NaN,lived,no,0,0,0,no
32,yes,adult,529427,37.2,60.0,NaN,warm,normal,normal_pink,less_3_sec,...,43.0,6.6,NaN,NaN,lived,yes,2209,0,0,no
219,yes,adult,535029,39.2,88.0,58.0,cold,absent,NaN,more_3_sec,...,NaN,NaN,cloudy,2.0,euthanized,no,3205,0,0,no
138,no,adult,534491,38.0,60.0,32.0,normal,normal,NaN,less_3_sec,...,50.0,7.0,clear,1.0,lived,no,0,0,0,no
250,no,adult,527940,36.6,42.0,18.0,cool,reduced,bright_pink,less_3_sec,...,52.0,7.1,NaN,NaN,died,yes,5111,0,0,no

In [15]:
df.describe(include='all')

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
count,299,299,2.990000e+02,239.000000,275.000000,241.000000,243,230,252,267,...,270.000000,266.000000,134,101.000000,299,299,299.000000,299.000000,299.000000,299
unique,2,2,NaN,NaN,NaN,NaN,4,4,6,3,...,NaN,NaN,3,NaN,3,2,NaN,NaN,NaN,2
top,yes,adult,NaN,NaN,NaN,NaN,cool,normal,normal_pink,less_3_sec,...,NaN,NaN,cloudy,NaN,lived,yes,NaN,NaN,NaN,no
freq,180,275,NaN,NaN,NaN,NaN,108,114,79,187,...,NaN,NaN,47,NaN,178,190,NaN,NaN,NaN,200
mean,NaN,NaN,1.087733e+06,38.168619,72.000000,30.460581,NaN,NaN,NaN,NaN,...,46.307407,24.274436,NaN,3.039604,NaN,NaN,3659.709030,90.528428,7.387960,NaN
std,NaN,NaN,1.532032e+06,0.733744,28.646219,17.666102,NaN,NaN,NaN,NaN,...,10.436743,27.364194,NaN,1.967947,NaN,NaN,5408.472421,650.637139,127.749768,NaN
min,NaN,NaN,5.184760e+05,35.400000,30.000000,8.000000,NaN,NaN,NaN,NaN,...,23.000000,3.300000,NaN,0.100000,NaN,NaN,0.000000,0.000000,0.000000,NaN
25%,NaN,NaN,5.289040e+05,37.800000,48.000000,18.000000,NaN,NaN,NaN,NaN,...,38.000000,6.500000,NaN,2.000000,NaN,NaN,2111.500000,0.000000,0.000000,NaN
50%,NaN,NaN,5.303010e+05,38.200000,64.000000,25.000000,NaN,NaN,NaN,NaN,...,45.000000,7.500000,NaN,2.300000,NaN,NaN,2322.000000,0.000000,0.000000,NaN
75%,NaN,NaN,5.347360e+05,38.500000,88.000000,36.000000,NaN,NaN,NaN,NaN,...,52.000000,56.750000,NaN,3.900000,NaN,NaN,3209.000000,0.000000,0.000000,NaN
max,NaN,NaN,5.305629e+06,40.800000,184.000000,96.000000,NaN,NaN,NaN,NaN,...,75.000000,89.000000,NaN,10.100000,NaN,NaN,41110.000000,7111.000000,2209.000000,NaN

In [16]:
df.shape

(299, 28)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   surgery                299 non-null    object
 1   age                    299 non-null    object
 2   hospital_number        299 non-null    int64
 3   rectal_temp            239 non-null    float64
 4   pulse                  275 non-null    float64
 5   respiratory_rate       241 non-null    float64
 6   temp_of_extremities    243 non-null    object
 7   peripheral_pulse       230 non-null    object
 8   mucous_membrane        252 non-null    object
 9   capillary_refill_time  267 non-null    object
 10  pain                   244 non-null    object
 11  peristalsis            255 non-null    object
 12  abdominal_distention   243 non-null    object
 13  nasogastric_tube       195 non-null    object
 14  nasogastric_reflux     193 non-null    object
 15  nasogastric_reflux_ph  53 non-null     float64
 16  rectal_exam_feces      197 non-null    object
 17  abdomen                181 non-null    object
 18  packed_cell_volume     270 non-null    float64
 19  total_protein          266 non-null    float64
 20  abdomo_appearance      134 non-null    object
 21  abdomo_protein         101 non-null    float64
 22  outcome                299 non-null    object
 23  surgical_lesion        299 non-null    object
 24  lesion_1               299 non-null    int64
 25  lesion_2               299 non-null    int64
 26  lesion_3               299 non-null    int64
 27  cp_data                299 non-null    object
dtypes: float64(7), int64(4), object(17)
memory usage: 65.5+ KB

In [17]:
df.duplicated().value_counts()

False    299
dtype: int64

In [18]:
 # Split df into X and y
y= df['outcome']
X= df.drop(['outcome'], axis=1)

## splitting data

In [19]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.40,random_state=123)
X_val,X_test,y_val,y_test=train_test_split(X_test,y_test,test_size=0.50,random_state=123)

In [20]:
X_train.to_csv("X_train.csv",index=False)
X_test.to_csv("X_test.csv",index=False)
y_train.to_csv("y_train.csv",index=False)
y_test.to_csv("y_test.csv",index=False)#X_val.to_csv("X_val.csv",index=False)
y_val.to_csv("y_val.csv",index=False)

In [21]:
print(X_train.shape,X_test.shape,X_val.shape,y_train.shape,y_test.shape,y_val.shape)

(179, 27) (60, 27) (60, 27) (179,) (60,) (60,)

## seperating numerical and categorical colums

In [22]:
numerical_cols=X_train.select_dtypes(exclude='object')

In [23]:
categorical_cols=X_train.select_dtypes(include='object')

In [24]:
numerical_cols

,hospital_number,rectal_temp,pulse,respiratory_rate,nasogastric_reflux_ph,packed_cell_volume,total_protein,abdomo_protein,lesion_1,lesion_2,lesion_3
291,530034,37.0,66.0,20.0,NaN,35.0,6.9,NaN,31110,0,0
297,530612,36.5,100.0,24.0,NaN,50.0,6.0,3.4,2208,0,0
231,5262543,38.5,30.0,18.0,NaN,40.0,7.7,NaN,2113,0,0
268,527883,39.3,64.0,90.0,6.5,39.0,6.7,NaN,31110,0,0
204,528151,38.5,100.0,NaN,NaN,NaN,NaN,NaN,4124,0,0
...,...,...,...,...,...,...,...,...,...,...,...
106,528668,38.3,52.0,96.0,NaN,43.0,6.1,NaN,3209,0,0
83,5279822,38.0,NaN,24.0,NaN,68.0,7.8,NaN,3205,0,0
17,526639,37.5,48.0,24.0,NaN,NaN,NaN,NaN,0,0,0
230,530028,39.5,92.0,28.0,NaN,72.0,6.4,3.6,3300,0,0
98,534135,37.7,44.0,40.0,NaN,41.0,60.0,NaN,0,0,0

In [25]:
categorical_cols

,surgery,age,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,pain,peristalsis,abdominal_distention,nasogastric_tube,nasogastric_reflux,rectal_exam_feces,abdomen,abdomo_appearance,surgical_lesion,cp_data
291,yes,adult,normal,reduced,bright_pink,less_3_sec,severe_pain,hypomotile,moderate,none,NaN,normal,distend_large,cloudy,yes,no
297,yes,adult,cool,reduced,pale_pink,less_3_sec,mild_pain,hypomotile,moderate,significant,none,absent,distend_small,serosanguious,yes,yes
231,yes,adult,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,no
268,yes,adult,warm,reduced,normal_pink,less_3_sec,NaN,hypomotile,none,none,less_1_liter,normal,distend_large,NaN,yes,no
204,no,adult,cool,reduced,bright_red,more_3_sec,severe_pain,hypomotile,severe,slight,none,absent,distend_large,NaN,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,yes,adult,NaN,reduced,pale_pink,less_3_sec,NaN,NaN,NaN,none,none,normal,NaN,NaN,yes,yes
83,yes,adult,cool,reduced,dark_cyanotic,more_3_sec,extreme_pain,NaN,severe,none,none,NaN,NaN,NaN,yes,no
17,no,adult,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,no
230,no,adult,cool,reduced,dark_cyanotic,less_3_sec,extreme_pain,absent,none,NaN,more_1_liter,absent,NaN,NaN,no,no
98,no,adult,warm,normal,pale_pink,less_3_sec,alert,hypomotile,slight,none,none,normal,distend_large,NaN,no,no

## Encoding categorical data

In [6]:
def binary_encode(df, columns, positive_values):
    df = df.copy()
    for column, positive_value in zip(columns, positive_values):
        df[column] = df[column].apply(lambda x: 1 if x == positive_value else 0)
    return df

def ordinal_encode(df, columns, orderings):
    df = df.copy()
    for column, ordering in zip(columns, orderings):
        df[column] = df[column].apply(lambda x: ordering.index(x))
    return df

def onehot_encode(df, columns, prefixes):
    df = df.copy()
    for column, prefix in zip(columns, prefixes):
        dummies = pd.get_dummies(df[column], prefix=prefix)
        df = pd.concat([df, dummies], axis=1)
        df = df.drop(column, axis=1)
    return df

## scaling numerical data

In [30]:
scaler=StandardScaler() #numerical_cols

In [ ]:
numerical_scaler=scaler.fit(numerical_cols)
numerical_scaler

In [28]:
scaled_data=numerical_scaler.transform(numerical_cols)

In [29]:
numerical_scaled_data=pd.DataFrame(scaled_data,columns=numerical_cols.columns)
numerical_scaled_data

,hospital_number,rectal_temp,pulse,respiratory_rate,nasogastric_reflux_ph,packed_cell_volume,total_protein,abdomo_protein,lesion_1,lesion_2,lesion_3
0,-0.393964,-1.588273,-0.227873,-0.560279,NaN,-1.031304,-0.594870,NaN,5.024019,-0.181313,-0.074953
1,-0.393608,-2.296166,0.914324,-0.341890,NaN,0.422517,-0.628439,0.277357,-0.278914,-0.181313,-0.074953
2,2.523910,0.535407,-1.437258,-0.669473,NaN,-0.546697,-0.565031,NaN,-0.296344,-0.181313,-0.074953
3,-0.395290,1.668036,-0.295061,3.261515,0.845145,-0.643619,-0.602330,NaN,5.024019,-0.181313,-0.074953
4,-0.395125,0.535407,0.914324,NaN,NaN,NaN,NaN,NaN,0.072633,-0.181313,-0.074953
...,...,...,...,...,...,...,...,...,...,...,...
174,-0.394806,0.252249,-0.698189,3.589097,NaN,-0.255933,-0.624709,NaN,-0.095251,-0.181313,-0.074953
175,2.534563,-0.172487,NaN,-0.341890,NaN,2.167102,-0.561301,NaN,-0.095985,-0.181313,-0.074953
176,-0.396057,-0.880380,-0.832565,-0.341890,NaN,NaN,NaN,NaN,-0.684037,-0.181313,-0.074953
177,-0.393968,1.951193,0.645572,-0.123502,NaN,2.554788,-0.613520,0.389349,-0.078554,-0.181313,-0.074953
178,-0.391436,-0.597223,-0.966942,0.531662,NaN,-0.449776,1.385699,NaN,-0.684037,-0.181313,-0.074953

In [7]:
def preprocess_inputs(df):
    df = df.copy()
    
    # Categorize categorical features
    binary_features = [
        'surgery',
        'age',
        'surgical_lesion',
        'cp_data'
    ]
    positive_values = [
        'yes',
        'adult',
        'yes',
        'yes'
    ]
    
    ordinal_features = [
        'temp_of_extremities',
        'peripheral_pulse',
        'capillary_refill_time',
        'pain',
        'peristalsis',
        'abdominal_distention',
        'nasogastric_tube',
        'nasogastric_reflux',
        'rectal_exam_feces'    ]
    orderings = [
        ['cold', 'cool', 'normal', 'warm'],
        ['absent', 'reduced', 'normal', 'increased'],
        ['less_3_sec', '3', 'more_3_sec'],
        ['alert', 'depressed', 'mild_pain', 'severe_pain', 'extreme_pain'],
        ['absent', 'hypomotile', 'normal', 'hypermotile'],
        ['none', 'slight', 'moderate', 'severe'],
        ['none', 'slight', 'significant'],
        ['none', 'less_1_liter', 'more_1_liter'],
        ['absent', 'decreased', 'normal', 'increased']
    ]
    
    nominal_features = [
        'hospital_number',
        'mucous_membrane',
        'abdomen',
        'abdomo_appearance'
    ]
    prefixes = [
        'HN',
        'MM',
        'AB',
        'AA'
    ]
    
    # Fill missing values
    for column in df.columns:
        if column in df.select_dtypes('object').columns:
            if column not in nominal_features:
                df[column] = df[column].fillna(df[column].mode()[0])
        else:
            df[column] = df[column].fillna(df[column].mean())# Encode categorical feature columns
    df = binary_encode(df, columns=binary_features, positive_values=positive_values)
    df = ordinal_encode(df, columns=ordinal_features, orderings=orderings)
    df = onehot_encode(df, columns=nominal_features, prefixes=prefixes)
    
     
    # Encode labels
    label_mapping = {'lived': 0, 'died': 1, 'euthanized': 2}
    df['outcome'] = df['outcome'].replace(label_mapping)
    
    # Split df into X and y
    y = df['outcome'].copy()
    X = df.drop('outcome', axis=1).copy()
    
    # Scale X with a standard scaler
    scaler = StandardScaler()
    X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
    
    return X, y

In [9]:
X, y = preprocess_inputs(df)

In [ ]:
{column: list(X[column].unique()) for column in X.select_dtypes('object').columns}

In [10]:
X

,surgery,age,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,capillary_refill_time,pain,peristalsis,...,MM_pale_cyanotic,MM_pale_pink,AB_distend_large,AB_distend_small,AB_firm,AB_normal,AB_other,AA_clear,AA_cloudy,AA_serosanguious
0,-1.229880,0.295420,0.506209,-0.218798,-0.155463,-0.473504,-1.088914,1.675999,1.731538,-1.185885,...,-0.398641,-0.485322,1.683251,-0.409840,-0.213201,-0.321436,-0.260494,-0.398641,-0.431866,-0.426401
1,0.813087,0.295420,1.575511,0.583463,-0.660914,-0.473504,0.671006,-0.601836,0.036841,-1.185885,...,2.508522,-0.485322,-0.594089,-0.409840,-0.213201,-0.321436,3.838859,-0.398641,2.315535,-0.426401
2,-1.229880,0.295420,0.200694,-1.166925,-0.408189,0.801970,0.671006,-0.601836,0.036841,-0.077824,...,-0.398641,2.060489,-0.594089,-0.409840,-0.213201,3.111040,-0.260494,-0.398641,-0.431866,-0.426401
3,0.813087,-3.385016,1.422753,3.354910,3.382695,-1.748977,0.671006,1.675999,-0.810507,-1.185885,...,-0.398641,-0.485322,-0.594089,-0.409840,-0.213201,-0.321436,-0.260494,-0.398641,-0.431866,2.345208
4,-1.229880,0.295420,-1.326880,1.166925,0.286807,-0.473504,0.671006,1.675999,0.036841,-0.077824,...,-0.398641,-0.485322,-0.594089,-0.409840,-0.213201,-0.321436,-0.260494,-0.398641,-0.431866,-0.426401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,0.813087,0.295420,0.000000,1.750388,2.498156,-1.748977,0.671006,1.675999,-0.810507,-1.185885,...,2.508522,-0.485322,1.683251,-0.409840,-0.213201,-0.321436,-0.260494,-0.398641,-0.431866,-0.426401
295,-1.229880,0.295420,-1.479638,0.000000,-0.408189,-0.473504,2.430926,1.675999,0.884190,-0.077824,...,2.508522,-0.485322,-0.594089,2.439977,-0.213201,-0.321436,-0.260494,-0.398641,-0.431866,2.345208
296,0.813087,0.295420,-1.021366,0.000000,-0.029100,-1.748977,-1.088914,-0.601836,0.884190,-1.185885,...,2.508522,-0.485322,1.683251,-0.409840,-0.213201,-0.321436,-0.260494,-0.398641,-0.431866,-0.426401
297,0.813087,0.295420,-2.548940,1.021059,-0.408189,-0.473504,-1.088914,-0.601836,0.036841,-0.077824,...,-0.398641,2.060489,-0.594089,2.439977,-0.213201,-0.321436,-0.260494,-0.398641,-0.431866,2.345208
298,0.813087,0.295420,-1.479638,-1.166925,-0.660914,-0.473504,0.671006,-0.601836,0.036841,-0.077824,...,-0.398641,-0.485322,-0.594089,-0.409840,-0.213201,3.111040,-0.260494,2.508522,-0.431866,-0.426401

In [11]:
y.value_counts()

0    178
1     77
2     44
Name: outcome, dtype: int64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=123)

In [13]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

print("Decision Tree Accuracy: {:.2f}%".format(model.score(X_test, y_test) * 100))

Decision Tree Accuracy: 60.00%

In [14]:
ensemble_model = RandomForestClassifier()
ensemble_model.fit(X_train, y_train)

print("Random Forest Accuracy: {:.2f}%".format(ensemble_model.score(X_test, y_test) * 100))

Random Forest Accuracy: 73.33%